-- Generated by Oracle SQL Developer Data Modeler 3.3.0.747
--   at:        2014-01-20 13:33:20 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE Aanvraag
  (
    naam                    VARCHAR2 (32) ,
    bestedingslimiet        NUMBER (32,32) ,
    jaarKosten              NUMBER (32,32) ,
    rente                   NUMBER (12,12) ,
    aanvraag_id             INTEGER NOT NULL ,
    Rekening_rekeningnummer VARCHAR2 (32 CHAR) NOT NULL
  ) ;
ALTER TABLE Aanvraag ADD CONSTRAINT Aanvraag_PK PRIMARY KEY
(
  aanvraag_id
)
;
ALTER TABLE Aanvraag ADD CONSTRAINT Aanvraag__UN UNIQUE
(
  Rekening_rekeningnummer
)
;

CREATE TABLE Bank
  (
    naam       VARCHAR2 (20 CHAR) ,
    straat     VARCHAR2 (23 CHAR) ,
    bank_id    INTEGER NOT NULL ,
    huisnummer VARCHAR2 (6 CHAR) ,
    postcode   VARCHAR2 (10 CHAR) ,
    plaats     VARCHAR2 (23 CHAR)
  ) ;
ALTER TABLE Bank ADD CONSTRAINT Bank_PK PRIMARY KEY
(
  bank_id
)
;

CREATE TABLE Creditcard
  (
    cardNummer              VARCHAR2 NOT NULL ,
    pincode                 INTEGER ,
    status                  VARCHAR2 (23 CHAR) ,
    vervalDatum             DATE ,
    Rekening_rekeningnummer VARCHAR2 (32 CHAR) NOT NULL
  ) ;
ALTER TABLE Creditcard ADD CONSTRAINT Creditcard_PK PRIMARY KEY
(
  cardNummer
)
;

CREATE TABLE Klant
  (
    voornaam             VARCHAR2 (32 CHAR) ,
    achternaam           VARCHAR2 (32 CHAR) ,
    straat               VARCHAR2 (32 CHAR) ,
    huisnummer           INTEGER ,
    postcode             VARCHAR2 ,
    woonplaats           VARCHAR2 (32 CHAR) ,
    geboortedatum        DATE ,
    email                VARCHAR2 (32 CHAR) ,
    klant_id             INTEGER NOT NULL ,
    bsn                  VARCHAR2 (32 CHAR) ,
    Studie_Studie_ID     INTEGER NOT NULL ,
    Aanvraag_aanvraag_id INTEGER NOT NULL ,
    Bank_bank_id         INTEGER NOT NULL
  ) ;
ALTER TABLE Klant ADD CONSTRAINT Medewerkerv1_PK PRIMARY KEY
(
  klant_id
)
;

CREATE TABLE Medewerker
  (
    voornaam      VARCHAR2 (32 CHAR) ,
    achternaam    VARCHAR2 (32 CHAR) ,
    straat        VARCHAR2 (32 CHAR) ,
    huisnummer    INTEGER ,
    postcode      VARCHAR2 ,
    woonplaats    VARCHAR2 (32 CHAR) ,
    geboortedatum DATE ,
    functie       VARCHAR2 (32 CHAR) ,
    salaris       NUMBER (32,32) ,
    email         VARCHAR2 (32 CHAR) ,
    medewerker_id INTEGER NOT NULL ,
    Bank_Bank_id  INTEGER NOT NULL
  ) ;
ALTER TABLE Medewerker ADD CONSTRAINT Medewerker_PK PRIMARY KEY
(
  medewerker_id
)
;

CREATE TABLE Rekening
  (
    rekeningnummer               VARCHAR2 (32 CHAR) NOT NULL ,
    saldo                        NUMBER (32,32) ,
    aanmaakDatum                 DATE ,
    status                       VARCHAR2 (23 CHAR) ,
    rekeningType_rekeningType_id INTEGER NOT NULL ,
    Klant_klant_id               INTEGER NOT NULL
  ) ;
ALTER TABLE Rekening ADD CONSTRAINT Rekening_PK PRIMARY KEY
(
  rekeningnummer
)
;

CREATE TABLE Studie
  (
    studie_ID          INTEGER NOT NULL ,
    naam               VARCHAR2 (32 CHAR) ,
    niveau             VARCHAR2 (32 CHAR) ,
    beginDatum         DATE ,
    eindDatum          DATE ,
    studiefinanciering VARCHAR2 (3 CHAR)
  ) ;
ALTER TABLE Studie ADD CONSTRAINT Studie_PK PRIMARY KEY
(
  studie_ID
)
;

CREATE TABLE Transactie
  (
    transactieNummer        VARCHAR2 (32 CHAR) NOT NULL ,
    status                  VARCHAR2 (32 CHAR) ,
    datum                   DATE ,
    bedrag                  NUMBER (32,32) ,
    Creditcard_cardNummer   VARCHAR2 NOT NULL ,
    Rekening_rekeningnummer VARCHAR2 (32 CHAR) NOT NULL
  ) ;
ALTER TABLE Transactie ADD CONSTRAINT Transactie_PK PRIMARY KEY
(
  transactieNummer
)
;

CREATE TABLE rekeningType
  (
    jaarKosten       NUMBER (32,32) ,
    bestedingsLimiet NUMBER (32,32) ,
    naam             VARCHAR2 (32) ,
    rente            NUMBER (12,12) ,
    rekeningType_id  INTEGER NOT NULL
  ) ;
ALTER TABLE rekeningType ADD CONSTRAINT rekeningType_PK PRIMARY KEY
(
  rekeningType_id
)
;

ALTER TABLE Aanvraag ADD CONSTRAINT Aanvraag_Rekening_FK FOREIGN KEY ( Rekening_rekeningnummer ) REFERENCES Rekening ( rekeningnummer ) ;

ALTER TABLE Creditcard ADD CONSTRAINT Creditcard_Rekening_FK FOREIGN KEY ( Rekening_rekeningnummer ) REFERENCES Rekening ( rekeningnummer ) ;

ALTER TABLE Klant ADD CONSTRAINT Klant_Aanvraag_FK FOREIGN KEY ( Aanvraag_aanvraag_id ) REFERENCES Aanvraag ( aanvraag_id ) ;

ALTER TABLE Klant ADD CONSTRAINT Klant_Bank_FK FOREIGN KEY ( Bank_bank_id ) REFERENCES Bank ( bank_id ) ;

ALTER TABLE Klant ADD CONSTRAINT Klant_Studie_FK FOREIGN KEY ( Studie_Studie_ID ) REFERENCES Studie ( studie_ID ) ;

ALTER TABLE Medewerker ADD CONSTRAINT Medewerker_Bank_FK FOREIGN KEY ( Bank_Bank_id ) REFERENCES Bank ( bank_id ) ;

ALTER TABLE Rekening ADD CONSTRAINT Rekening_Klant_FK FOREIGN KEY ( Klant_klant_id ) REFERENCES Klant ( klant_id ) ;

ALTER TABLE Rekening ADD CONSTRAINT Rekening_rekeningType_FK FOREIGN KEY ( rekeningType_rekeningType_id ) REFERENCES rekeningType ( rekeningType_id ) ;

ALTER TABLE Transactie ADD CONSTRAINT Transactie_Creditcard_FK FOREIGN KEY ( Creditcard_cardNummer ) REFERENCES Creditcard ( cardNummer ) ;

ALTER TABLE Transactie ADD CONSTRAINT Transactie_Rekening_FK FOREIGN KEY ( Rekening_rekeningnummer ) REFERENCES Rekening ( rekeningnummer ) ;

CREATE SEQUENCE Aanvraag_aanvraag_id_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER aanvraag_id_auto_increment BEFORE
  INSERT ON Aanvraag FOR EACH ROW WHEN (NEW.aanvraag_id IS NULL) BEGIN
  SELECT Aanvraag_aanvraag_id_SEQ.NEXTVAL INTO :NEW.aanvraag_id FROM DUAL;
END;
/

CREATE SEQUENCE Klant_klant_id_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER klant_id_auto_increment BEFORE
  INSERT ON Klant FOR EACH ROW WHEN (NEW.klant_id IS NULL) BEGIN
  SELECT Klant_klant_id_SEQ.NEXTVAL INTO :NEW.klant_id FROM DUAL;
END;
/

CREATE SEQUENCE Medewerker_medewerker_id_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER medewerker_id_auto_increment BEFORE
  INSERT ON Medewerker FOR EACH ROW WHEN (NEW.medewerker_id IS NULL) BEGIN
  SELECT Medewerker_medewerker_id_SEQ.NEXTVAL INTO :NEW.medewerker_id FROM DUAL;
END;
/

CREATE SEQUENCE Studie_studie_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER studie_id_auto_increment BEFORE
  INSERT ON Studie FOR EACH ROW WHEN (NEW.studie_ID IS NULL) BEGIN
  SELECT Studie_studie_ID_SEQ.NEXTVAL INTO :NEW.studie_ID FROM DUAL;
END;
/

CREATE SEQUENCE rekeningType_rekeningType_id START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER rekeningType_id_trigger BEFORE
  INSERT ON rekeningType FOR EACH ROW WHEN (NEW.rekeningType_id IS NULL) BEGIN
  SELECT rekeningType_rekeningType_id.NEXTVAL
  INTO :NEW.rekeningType_id
  FROM DUAL;
END;
/


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             20
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
